apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-pod
  name: nginx-pod
spec:
  containers:
  - command:
    - sh
    - -c
    - |
      echo "start..."
      tail -f /dev/null
    image: busybox
    imagePullPolicy: IfNotPresent
    name: nginx-pod-container
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 200m
        memory: 256Mi